"""
@file arm_measure_sim.launch.py
@brief 参数辨识仿真场景（旧版链路，依赖已不存在的 parameter_measure 包）

启动内容（按实际启动顺序）：
  1. robot_state_publisher  ：发布 /robot_description 与 TF
  2. mujoco_ros2_control    ：ros2_control_node + MuJoCo SystemInterface 插件
  3. sim_pid_controller     ：链式 PID 控制器
  4. arm_controller         ：机械臂状态机控制器
  5. parameter_measure      ：独立的参数辨识节点，通过 myjoints_state / myjoints_target
                              话题与控制器交换数据并落盘 CSV

@warning 状态：当前仓库不可用。parameter_measure 包已不存在（现为 parameter_identify，
         且只提供 identify_arm 可执行文件）；参数辨识现在由控制器内部的
         ParamterMeasureState 完成，由 tasks 的 measure 任务触发，不再需要独立节点：
             ros2 run tasks task_runner --ros-args -p task_sequence:="[measure]"
         另外本文件没有 spawn joint_state_broadcaster，/joint_states 依赖旧链路的
         parameter_measure 节点发布，与当前控制器不匹配。
@note show_rviz / csv_file_path / trajectory_file_path 等 launch 参数在当前链路下没有消费方
      （本文件也没有启动 rviz2）。
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, LogInfo, RegisterEventHandler, Shutdown
from launch.event_handlers import OnProcessExit, OnProcessStart
from launch.substitutions import Command, FindExecutable, LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue, ParameterFile
from ament_index_python.packages import get_package_share_directory
import os


def generate_launch_description():
    arm_model_share = get_package_share_directory("arm_model")
    launch_pack_share = get_package_share_directory("launch_pack")

    urdf_path = os.path.join(arm_model_share, "model", "robotic_arm.urdf")
    controller_yaml = os.path.join(launch_pack_share, "config", "ros2_controller.yaml")
    rviz_path = os.path.join(launch_pack_share, "rviz", "display_config.rviz")

    # 通过 xacro 处理 URDF，使硬件标签里的 $(find arm_model) 被正确展开，
    # MJCF 场景由 URDF 的 <ros2_control> 硬件标签指定：
    #   $(find arm_model)/model/scene.xml
    robot_description_content = Command(
        [
            PathJoinSubstitution([FindExecutable(name="xacro")]),
            " ",
            urdf_path,
        ]
    )
    robot_description = {
        "robot_description": ParameterValue(robot_description_content, value_type=str)
    }

    trajectory_file_path_arg = DeclareLaunchArgument(
        "trajectory_file_path",
        default_value="",
        description="Expected joint-position trajectory CSV generated by parameter_identify",
    )

    csv_file_path_arg = DeclareLaunchArgument(
        "csv_file_path",
        default_value="",
        description="Output CSV path for measured joint position/velocity/torque data",
    )

    move_to_start_duration_arg = DeclareLaunchArgument(
        "move_to_start_duration",
        default_value="3.0",
        description="Duration in seconds for quintic interpolation from current pose to trajectory start",
    )

    control_period_arg = DeclareLaunchArgument(
        "control_period",
        default_value="0.02",
        description="Measurement command publish period in seconds",
    )

    discard_initial_samples_arg = DeclareLaunchArgument(
        "discard_initial_samples",
        default_value="5",
        description="Number of initial recorded samples to discard after trajectory playback starts",
    )

    start_measure_arg = DeclareLaunchArgument(
        "start_measure",
        default_value="false",
        description="Whether parameter_measure should start immediately after launch",
    )

    show_rviz_arg = DeclareLaunchArgument(
        "show_rviz",
        default_value="true",
        description="Whether to start RViz2 together with measurement simulation",
    )

    robot_state_pub = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        parameters=[robot_description],
        output="screen",
    )

    # 新版 mujoco_ros2_control：MuJoCo 以 SystemInterface 插件运行在
    # controller_manager 进程内，由 URDF 的 <ros2_control> 标签加载。
    mujoco = Node(
        package="mujoco_ros2_control",
        executable="ros2_control_node",
        output="both",
        parameters=[
            {"use_sim_time": True},
            ParameterFile(controller_yaml),
        ],
        on_exit=Shutdown(),
    )

    sim_pid_controller = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["sim_pid_controller", "--controller-manager", "/controller_manager"],
        output="screen",
    )

    arm_controller = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["arm_controller", "--controller-manager", "/controller_manager"],
        output="screen",
    )

    # 注意：parameter_measure 包已不存在（现为 parameter_identify，仅提供 identify_arm）；
    # 参数辨识现在由控制器 ParamterMeasureState + tasks 的 measure 任务完成，本节点已废弃。
    parameter_measure = Node(
        package="parameter_measure",
        executable="parameter_measure_node",
        output="screen",
        parameters=[
            {
                "model_path": urdf_path,
                "joint_state_topic": "myjoints_state",
                "joint_target_topic": "myjoints_target",
                "trajectory_file_path": LaunchConfiguration("trajectory_file_path"),
                "csv_file_path": LaunchConfiguration("csv_file_path"),
                "move_to_start_duration": LaunchConfiguration("move_to_start_duration"),
                "control_period": LaunchConfiguration("control_period"),
                "discard_initial_samples": LaunchConfiguration("discard_initial_samples"),
                "start_measure": LaunchConfiguration("start_measure"),
            }
        ],
    )

    load_controller = RegisterEventHandler(
        OnProcessStart(
            target_action=mujoco,
            on_start=[
                LogInfo(msg="MuJoCo ros2_control node started, spawning sim_pid_controller"),
                sim_pid_controller,
            ],
        )
    )

    load_arm_controller = RegisterEventHandler(
        OnProcessExit(
            target_action=sim_pid_controller,
            on_exit=[
                LogInfo(msg="sim_pid_controller spawned, spawning arm_controller"),
                arm_controller,
            ],
        )
    )

    return LaunchDescription(
        [
            show_rviz_arg,
            trajectory_file_path_arg,
            csv_file_path_arg,
            move_to_start_duration_arg,
            control_period_arg,
            discard_initial_samples_arg,
            start_measure_arg,
            robot_state_pub,
            mujoco,
            load_controller,
            load_arm_controller,
            parameter_measure,
        ]
    )
